# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ============================================================
# NOTICE
# ============================================================
# This docker-compose file is for validating releases only. To use StreamPipes, use the installation instructions
# provided on https://streampipes.apache.org/download
#


version: "2.4"
services:

  #### apache/incubator-streampipes
  backend:
    build:
      context: ./streampipes-backend
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: adoptopenjdk/openjdk8-openj9:alpine-slim
    depends_on:
      - consul
      - couchdb
    networks:
      spnet:

  connect-master:
    build:
      context: ./streampipes-connect-container-master
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: adoptopenjdk/openjdk8-openj9:alpine-slim
    depends_on:
      - consul
      - couchdb
    environment:
      - EXECUTION_MODE=MASTER
      - SP_CONNECT_CONTAINER_HOST=connect-master
      - SP_CONNECT_CONTAINER_WORKER=connect-worker
    networks:
      spnet:

  nginx:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: nginx
    ports:
      - "80:80"
    depends_on:
      - couchdb
      - activemq
      - consul
      - connect-master
      - backend
    networks:
      spnet:

  #### Mandatory external services
  activemq:
    image: fogsyio/activemq:5.15.9
    networks:
      spnet:

  consul:
    image: fogsyio/consul:1.7.1
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - "CONSUL_BIND_INTERFACE=eth0"
      - "CONSUL_HTTP_ADDR=0.0.0.0"
    entrypoint:
      - consul
      - agent
      - -server
      - -bootstrap-expect=1
      - -data-dir=/consul/data
      - -node=consul-one
      - -bind={{ GetInterfaceIP "eth0" }}
      - -client=0.0.0.0
      - -enable-script-checks=true
      - -ui
    networks:
      spnet:
        ipv4_address: 172.31.0.9

  couchdb:
    image: fogsyio/couchdb:2.3.1
    networks:
      spnet:

  kafka:
    image: fogsyio/kafka:2.2.0
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      # see: https://github.com/confluentinc/schema-registry/issues/648
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      spnet:

  zookeeper:
    image: fogsyio/zookeeper:3.4.13
    networks:
      spnet:

  influxdb:
    image: fogsyio/influxdb:1.7
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_ADMIN_ENABLED=true
    networks:
      spnet:

networks:
  spnet:
    driver: bridge
    name: streampipes_network
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1
